### PR TITLE
Adds .NetCore 3.0 support

### PR DESCRIPTION
**Pull request by dotMorten**
This fixes lucky issue #13 
Notes:
 -  This requires you to install .NET Core 3.0 Preview to build
 - .NET Core needs to force using STA for these tests (at least for now until MSTest addresses this)
 - Adds a second test project that executes in the context of .NET Core
 - Note that one of the unit tests throws a slightly more specific exception on .NET Core

All tests pass:
image

### CODE REVIEW

**Comment by PedroLamas** [comment]
@dotMorten seems there's some conflicts, care to take a quick stab in clearing those?

**Comment by dotMorten** [comment]
There are conflicts because you merged my other PR 😁 I'll address a bit later today

**Comment by batzen** [comment]
What's blocking this PR from getting merged?

**Comment by HanbGao** [comment]
> 是什么阻止了这个公关合并？



> 是什么阻止了这个公关合并？


I found some new problems in .NET Core 3.0 Preview
1.when use it will show the warning below:

Warning	NU1701	Package 'Microsoft.Xaml.Behaviors.Wpf 1.0.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.	StarPayToolkit.AuditAndRefund
2.If publish a single-file executable with dotnet publish，the application will get an error

**Comment by dotMorten** [comment]
> What's blocking this PR from getting merged?

.net core 3.0 hasn't shipped yet

**Comment by batzen** [comment]
So you suggest that no one should publish packages supporting previews of .net core 3.0?

**Comment by dotMorten** [comment]
They would at least have to be marked "preview". IMHO better to keep this a branch till around launch date. Especially considering this library should work already (apart from the warning)

**Comment by bizzbizz** [comment]
First of all thanks for your great work. All seems fine on my machine, except for the **UnitTests.NetCore** project:
There is the **NU1701** warning with **MSTest.STAExtensions 1.0.3-beta** causing this error:

> Message: Initialization method Microsoft.Xaml.Interactions.UnitTests.ActionTest.Setup threw exception. System.IO.FileLoadException: The given assembly name or codebase, '\Test\UnitTests.NetCore\bin\Debug\netcoreapp3.0\Microsoft.Xaml.Behaviors.dll', was invalid..

**Comment by batzen** [comment]
So .NET core 3.0 is GA.
What's the plan on merging this? I guess it would first have to be updated to use the GA release.
That would allow us to enable NU warnings again.

**Comment by brianlagunas** [comment]
I have a meeting with MS on Oct 9th to talk about the handling of this project.

**Comment by dotMorten** [comment]
Sync'ed up with master and cleaned up a bit, but needs some more work. At this point `DO NOT MERGE`

**Comment by brian-pickens-web** [comment]
Looking forward to netcore3.0 support!

**Comment by dotMorten** [comment]
@brian-pickens-web you can use my branch now. Mainly can't merge due to some unit test issues

**Comment by mauroservienti** [comment]
Do I get it right that you’re suggesting that if someone is blocked by the lack of behaviors in NET Core 3 the way forward till this is merged is:

- clone this repo
- use this branch
- build yourself 
- directly reference built artifacts (while waiting for official nuget package)

**Comment by dotMorten** [comment]
@mauroservienti Yes. Is that a problem? Isn't that the entire benefit of open source?

**Comment by dotMorten** [comment]
OK Finally figured out the unit test issue. PR ready to go!

**Comment by mauroservienti** [comment]
@dotMorten 

> Is that a problem? Isn't that the entire benefit of open source?

Yes and no. It’s doable, even if I’d prefer to not be required to support someone else code in production. Especially if it’s MS code, like in this case, even if it could be for a short period of time. What we can do for sure is proceeded, using the mentioned plan, with the upgrade process and then wait for this PR to be merged and released.

**Comment by dotMorten** [comment]
FYI the Azure DevOps build failure is because VS 16.3 now requires you to target net472 for the DesignTools library. I believe this was an unintended breaking change, as it could break usage by older editors.
I've mentioned this to @LyalinDotCom, and he said he would take a look. Also paging @diverdan92

**Comment by brianlagunas** [comment]
We are targeting a Nov 4 release date. We are waiting on some issues with the build pipeline to be fixed.

**Comment by dotMorten** [comment]
Until then you can just grab the artifact from the pipeline:
https://dev.azure.com/dotnet/XamlBehaviorsWpf/_build/results?buildId=22944&view=artifacts

**Comment by DVaughan** [comment]
This PR is now published [on NuGet](https://www.nuget.org/packages/Microsoft.Xaml.Behaviors.Wpf/)

**Pull request merged**
